import assert from "node:assert/strict";
import { cp, mkdir, mkdtemp, readFile, writeFile } from "node:fs/promises";
import { spawnSync } from "node:child_process";
import { tmpdir } from "node:os";
import { resolve } from "node:path";
import test from "node:test";

const root = resolve(import.meta.dirname, "..");
const readJson = async (path) => JSON.parse(await readFile(resolve(root, path), "utf8"));

test("dependency manifest is pinned, licensed, host-aware, and policy-complete", async () => {
  const manifest = await readJson("skills.manifest.json");
  const lock = await readJson("skills-lock.json");
  assert.equal(manifest.schemaVersion, 1);
  assert.equal(lock.dependencies.length, manifest.dependencies.length);

  const ids = new Set();
  for (const dependency of manifest.dependencies) {
    assert.ok(!ids.has(dependency.id), `duplicate dependency ${dependency.id}`);
    ids.add(dependency.id);
    assert.ok(["required", "conditional", "optional"].includes(dependency.status));
    assert.ok(dependency.hosts.length > 0);
    assert.ok(dependency.hosts.every((host) => ["claude", "codex"].includes(host)));
    assert.ok(dependency.license.length >= 2);
    assert.ok(dependency.source.url.startsWith("https://"));
    assert.ok(dependency.resolved.kind && dependency.resolved.value);
    if (dependency.installer.kind !== "manual") {
      assert.ok(["commit", "version"].includes(dependency.resolved.kind));
      assert.ok(!/latest|\bmain\b|\bmaster\b/.test(dependency.resolved.value));
    }
    assert.ok(dependency.trust.level && dependency.trust.review);
    assert.ok(dependency.invocation.policy);
    assert.ok(dependency.installer.kind);
  }

  assert.equal(manifest.dependencies.find(({ id }) => id === "flutter-official").source.url,
    "https://github.com/flutter/agent-plugins");
  assert.equal(manifest.dependencies.find(({ id }) => id === "mobile-mcp").resolved.value, "1.0.2");
  assert.ok(![...ids].some((id) => /ponytail|rocketsim|codex-plugin/i.test(id)));

  const lockCheck = spawnSync("node", ["scripts/update-lock.mjs", "--check"], { cwd: root, encoding: "utf8" });
  assert.equal(lockCheck.status, 0, lockCheck.stderr);

  const schemas = spawnSync("node", ["scripts/validate-json-schema.mjs"], { cwd: root, encoding: "utf8" });
  assert.equal(schemas.status, 0, schemas.stderr);
  const fixture = await mkdtemp(resolve(tmpdir(), "the-lab-schema-"));
  const invalidManifest = resolve(fixture, "manifest.json");
  const invalid = structuredClone(manifest);
  delete invalid.dependencies[0].license;
  await writeFile(invalidManifest, JSON.stringify(invalid));
  const rejected = spawnSync("node", ["scripts/validate-json-schema.mjs", "--document", invalidManifest,
    "--schema", resolve(root, "schemas/skills-manifest.schema.json")], { cwd: root, encoding: "utf8" });
  assert.notEqual(rejected.status, 0);
  assert.match(rejected.stderr, /missing required property license/);
});

test("one catalog generates 14 drift-checked host adapters", async () => {
  const catalog = await readJson("roles/catalog.json");
  const checksums = await readJson("generated/role-checksums.json");
  assert.equal(catalog.roles.length, 14);
  assert.deepEqual(Object.keys(checksums.roles).sort(), catalog.roles.map(({ id }) => id).sort());

  const generation = spawnSync("node", ["scripts/generate-role-adapters.mjs", "--check"], {
    cwd: root,
    encoding: "utf8"
  });
  assert.equal(generation.status, 0, generation.stderr);

  for (const role of catalog.roles) {
    const claude = await readFile(resolve(root, `agents/${role.id}.md`), "utf8");
    const codex = await readFile(resolve(root, `.codex/agents/${role.id}.toml`), "utf8");
    assert.match(claude, /GENERATED by scripts\/generate-role-adapters\.mjs/);
    assert.match(codex, /developer_instructions = '''/);
    assert.match(codex, new RegExp(`THE_LAB_ROLE = "${role.id}"`));
    if (role.writePolicy === "none") {
      assert.match(codex, /sandbox_mode = "read-only"/);
      assert.match(claude, /permissionMode: plan/);
    }
  }

  const mobile = await readFile(resolve(root, ".codex/agents/mobile-qa.toml"), "utf8");
  assert.match(mobile, /@mobilenext\/mobile-mcp@1\.0\.2/);
  assert.match(mobile, /MOBILEMCP_DISABLE_TELEMETRY = "1"/);
  assert.doesNotMatch(mobile, /mobile_(launch|terminate|install|uninstall|set_orientation|open_url)/);

  const fixture = await mkdtemp(resolve(tmpdir(), "the-lab-drift-"));
  await mkdir(resolve(fixture, "scripts"));
  await cp(resolve(root, "scripts/generate-role-adapters.mjs"), resolve(fixture, "scripts/generate-role-adapters.mjs"));
  await cp(resolve(root, "roles"), resolve(fixture, "roles"), { recursive: true });
  assert.equal(spawnSync("node", ["scripts/generate-role-adapters.mjs"], { cwd: fixture }).status, 0);
  const drifted = resolve(fixture, "agents/discovery.md");
  await writeFile(drifted, `${await readFile(drifted, "utf8")}\nhand edit\n`);
  const drift = spawnSync("node", ["scripts/generate-role-adapters.mjs", "--check"], { cwd: fixture, encoding: "utf8" });
  assert.notEqual(drift.status, 0);
  assert.match(drift.stderr, /generated adapter drift/);
});
